version: '3'
services:

  prometheus:
    image: prom/prometheus:v1.7.1
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    command: -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles

  grafana:
    image: grafana/grafana:4.3.2
    ports: 
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_DASHBOARDS_JSON_ENABLED=true

  cadvisor:
    image: google/cadvisor:v0.26.1
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro

  apache:
    image: nasoym/httpd-mod_jk
    ports:
      - 8080:80
    depends_on:
      - worker1
      - worker2
    volumes:
      - ./config/jk.conf:/etc/apache2/mods-available/jk.conf
      - ./config/workers.properties:/etc/libapache2-mod-jk/workers.properties
      - ./config/httpd_extra.conf:/usr/local/apache2/conf/httpd_extra.conf
    command: /bin/bash -c 'echo "" >> /usr/local/apache2/conf/httpd.conf; echo "Include /usr/local/apache2/conf/httpd_extra.conf" >> /usr/local/apache2/conf/httpd.conf; httpd-foreground'

  apache_exporter:
    image: ghellings/apache_exporter
    depends_on:
      - apache
    command: -scrape_uri http://apache/server-status/?auto
      
  worker1:
    image: nasoym/tomcat-dummy-service

  worker2:
    image: nasoym/tomcat-dummy-service

  benchmark:
    image: debian:jessie
    depends_on:
      - apache
    volumes:
      - ./config/grafana_setup.sh:/grafana_setup.sh:ro
      - ./config/benchmark.sh:/benchmark.sh:ro
      - ./config/grafana:/grafana:ro
      - ./config/grafana_render:/grafana_render
    command: /bin/sh -c "apt-get update; apt-get install -y apache2-utils curl jq siege; ./benchmark.sh"

