#!/usr/bin/env bash

set -eufo pipefail

: ${project_name:="$(basename $(pwd))"}

if [[ -z "$@" ]]; then 
  echo "instance[s] name must be provided" >&2
  exit 1
fi

ec2 ssh $@ <<EOF
  cd ${project_name}
  docker-compose down -v --remove-orphans
EOF

