#!/usr/bin/env bash

set -eufo pipefail

: ${project_name:="$(basename $(pwd))"}

if [[ -z "$@" ]]; then 
  echo "instance[s] name must be provided" >&2
  exit 1
fi

ec2 ssh $@ <<EOF
  mkdir -p ${project_name}
  mkdir -p ${project_name}/config
  sudo chown -R ec2-user:ec2-user ${project_name}/config
EOF

ec2 scp $@ ${project_name} config
ec2 scp $@ ${project_name} docker-compose.yml

ec2 ssh $@ <<EOF
  cd ${project_name}
  export HOST_IP_ADDRESS="\$(hostname -i)"
  docker-compose -p ${project_name} up -d --remove-orphans
  docker-compose -p ${project_name} kill -s HUP haproxy
  curl -s -i -XPOST "http://localhost:9090/-/reload"
  docker-compose -p ${project_name} exec -T apache /bin/bash -c '/usr/local/apache2/bin/apachectl -k graceful'

EOF
  # docker-compose -p ${project_name} kill -s HUP apache
  # docker-compose -p ${project_name} kill -s SIGUSR1 apache
  # docker-compose -p ${project_name} exec -T apache /bin/bash -c '/usr/local/apache2/bin/apachectl -k restart'
  # docker-compose -p ${project_name} exec -T apache /bin/bash -c '/usr/local/apache2/bin/apachectl -k graceful'

