#!/usr/bin/env bash

set -eufo pipefail

: ${project_name:="$(basename $(pwd))"}

if [[ -z "$@" ]]; then 
  echo "instance[s] name must be provided" >&2
  exit 1
fi

ec2 ssh $@ <<EOF
  mkdir -p ${project_name}
  mkdir -p ${project_name}/config
  sudo chown -R ec2-user:ec2-user ${project_name}/config
EOF

ec2 scp $@ ${project_name} config
ec2 scp $@ ${project_name} docker-compose.yml

: ${delay:="3"}
: ${concurrent:="30"}
: ${initial_wait:="0"}
: ${siege_path:="/hello/cpu"}
: ${name:="stress1"}

ec2 ssh $@ <<EOF
  cd ${project_name}
  export HOST_IP_ADDRESS="\$(hostname -i)"

  for i in {1..3}; do 
    docker run \
      -d \
      --restart unless-stopped \
      --name stress\${i} \
      --network apachemodjksetup_default \
      --log-opt max-size=10m \
      nasoym/http_stress_tester \
      siege -c1000 -t24H -d5 http://haproxy/hello/get_wait 
  done


EOF


