#!/usr/bin/env bash

set -eufo pipefail

: ${project_name:="$(basename $(pwd))"}

if [[ -z "$@" ]]; then 
  echo "instance[s] name must be provided" >&2
  exit 1
fi

ec2 ssh $@ <<EOF
  mkdir -p ${project_name}
  mkdir -p ${project_name}/config
  sudo chown -R ec2-user:ec2-user ${project_name}/config
EOF

ec2 scp $@ ${project_name} config
ec2 scp $@ ${project_name} docker-compose.yml

: ${delay:="3"}
: ${concurrent:="30"}
: ${initial_wait:="0"}
: ${siege_path:="/hello/cpu"}
: ${name:="stress1"}

ec2 ssh $@ <<EOF
  cd ${project_name}
  export HOST_IP_ADDRESS="\$(hostname -i)"
  docker run \
    -d \
    --restart always \
    --name ${name} \
    -e initial_wait=${initial_wait} \
    -e concurrent=${concurrent} \
    -e delay=${delay} \
    -e siege_path="${siege_path}" \
    --network apachemodjksetup_default \
    -v \$(pwd)/config/stress.sh:/stress.sh \
    debian:jessie \
    /bin/sh -c "apt-get update; apt-get install -y curl siege;./stress.sh"

EOF


