#!/usr/bin/env bash

set -eufo pipefail

provision="$(dirname $(realpath $0))/../provision"
project_name="$(basename $(dirname $(realpath $0)))"

echo "
${project_name}_monitoring
" | ec2 create 

  ec2 ssh ${project_name}_monitoring <<EOF
sudo yum install -y docker
sudo service docker start
sudo usermod -a -G docker ec2-user
sudo pip install docker-compose
EOF

  ec2 ssh ${project_name}_monitoring <<EOF
  mkdir -p ${project_name}
  cd ${project_name}
  echo "$(cat docker-compose.yml)" > docker-compose.yml
  docker-compose up -d
EOF

