#!/usr/bin/env bash

set -eufo pipefail

: ${project_name:="docker_host"}

consul_server="$1"
# ec2 details monitoring | jq -r '.PrivateIpAddresses[0]'
shift

if [[ -z "$@" ]]; then 
  echo "instance[s] name must be provided" >&2
  exit 1
fi

provision_ec2 docker $@

ec2 ssh $@ <<EOF
  mkdir -p ${project_name}
  # mkdir -p ${project_name}/bss_handlers
  # sudo chown -R ec2-user:ec2-user ${project_name}/bss_handlers
EOF

ec2 scp $@ ${project_name} bss_handlers

ec2 ssh $@ <<EOF
  cd ${project_name}
  export HOST_IP_ADDRESS="\$(hostname -i)"
  docker rm -vf registrator 
  docker run -d --name=registrator \
    --net host \
    --volume=/var/run/docker.sock:/tmp/docker.sock \
    gliderlabs/registrator -ip \${HOST_IP_ADDRESS} consul://${consul_server}:8500

  docker rm -vf bss 
  docker run -d \
    --name bss \
    -e "SERVICE_NAME=bss_bss" \
    -e "SERVICE_TAGS=monitored,path=prometheus" \
    -P \
    --volume=\$(pwd)/bss_handlers:/bss/handlers \
    nasoym/bss_docker
  
EOF

