#!/usr/bin/env bash

set -eufo pipefail

provision="$(dirname $(realpath $0))/../provision"
project_name="$(basename $(dirname $(realpath $0)))"

echo "
${project_name}_worker1
" | ec2 create 

$provision docker ${project_name}_worker1

$provision ssh ${project_name}_worker1 <<EOF
  mkdir -p ${project_name}
  cd ${project_name}
  echo "$(cat docker-compose.yml)" > docker-compose.yml
  docker-compose up -d
EOF

