#!/usr/bin/env bash

set -eufo pipefail

project_name="$(basename $(dirname $(realpath $0)))"

ec2 list running \
  | jq -c --arg project "$project_name" \
    'map(select(.Name|startswith($project)))' \
  | jq -r 'map(.Name)[]' \
  | ec2 delete

