#!/usr/bin/env bash

set -eufo pipefail

: ${project_name:="grafana"}

ec2 ssh $@ <<EOF
  mkdir -p ${project_name}
EOF

ec2 scp $@ ${project_name} add_datasources
ec2 scp $@ ${project_name} docker-compose.yml

ec2 ssh $@ <<EOF
  cd ${project_name}

  docker-compose up -d --remove-orphans

  for i in {1..20}; do 
    curl -s "http://localhost:3000" >/dev/null && break
    sleep 1
  done
  curl -s "http://localhost:3000" >/dev/null || { echo "grafana did not respond!" >&2; exit 1;}
  ./add_datasources

EOF


