#!/usr/bin/env bash

set -eufo pipefail

: ${project_name:="monitoring"}

ec2 scp $@ ${project_name} prometheus.yml
ec2 scp $@ ${project_name} docker-compose.yml

ec2 ssh $@ <<EOF
  cd ${project_name}
  docker-compose -p ${project_name} up -d --remove-orphans
  curl -s -X POST "http://localhost:9090/-/reload"
EOF

