#!/usr/bin/env bash

set -eufo pipefail

: ${project_name:="$(basename $(pwd))"}

if [[ -z "$@" ]]; then 
  echo "instance[s] name must be provided" >&2
  exit 1
fi


ec2 scp_get $@ haproxy_worker_setup_1/config/grafana_render/*.png ./config/grafana_render/

