version: '3'
services:

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports: 
      - 3000:3000
    environment:
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,mtanda-heatmap-epoch-panel,mtanda-histogram-panel,grafana-piechart-panel,jdbranham-diagram-panel
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    external_links:
      - cadvisor
      - node_exporter
    # command: -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles
    networks:
      - foobridge
      # - monitoring

networks:
  foobridge:
    external:
      name: bridge
  monitoring:
 
