global:
  scrape_interval: 2s
  scrape_timeout: 1s
scrape_configs:
  - job_name: 'worker'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['worker1:8080','worker2:8080']
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy_exporter:9101']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

