global:
  scrape_interval: 2s
  scrape_timeout: 1s
scrape_configs:
  - job_name: 'worker'
    metrics_path: '/hello/prometheus'
    static_configs:
      - targets: ['worker1:8080','worker2:8080','worker3:8080']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy_exporter:9101']
  - job_name: 'apache'
    static_configs:
      - targets: ['apache_exporter:9117']
  - job_name: 'apache_mod_jk'
    static_configs:
      - targets: ['apache_mod_jk_exporter:8080']

