global:
  scrape_interval: 2s
  scrape_timeout: 1s
scrape_configs:
  - job_name: 'worker'
    metrics_path: '/hello/prometheus'
    static_configs:
      - targets: ['worker1:8080','worker2:8080']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'apache'
    static_configs:
      - targets: ['apache_exporter:9117']

