#!/usr/bin/env bash

set -eufo pipefail

: ${project_name:="monitoring"}

if [[ -z "$@" ]]; then 
  echo "instance[s] name must be provided" >&2
  exit 1
fi

provision_ec2 docker $@

ec2 ssh $@ <<EOF
  mkdir -p ${project_name}
  mkdir -p ${project_name}/scripted_dashboards
  sudo chown -R ec2-user:ec2-user ${project_name}/scripted_dashboards
  mkdir -p ${project_name}/node_exporter_text
  sudo chown -R ec2-user:ec2-user ${project_name}/node_exporter_text
EOF

ec2 scp $@ ${project_name} targets.yml
ec2 scp $@ ${project_name} prometheus.yml
ec2 scp $@ ${project_name} docker-compose.yml
ec2 scp $@ ${project_name} scripted_dashboards

ec2 ssh $@ <<EOF
  cd ${project_name}
  docker-compose -p ${project_name} up -d --remove-orphans
  curl -s -X POST "http://localhost:9090/-/reload"
EOF

